### ISSUE TITLE
Fix testing suite

### ISSUE THREAD

**Issue by saulshanabrook** [Quansight/ibis-vega-transform#45]
In https://github.com/Quansight/ibis-vega-transform/pull/41 I broke the tests, we should update the saved SVGs to match what is in master.

**Comment by goanpeca** [comment]
Working on this right now

**Comment by goanpeca** [comment]
Ok now I can work on this for sure!

**Comment by saulshanabrook** [comment]
From vega folks

> Yeah I would await runAsync then just lookup the signal on the view

**Comment by saulshanabrook** [comment]
LMK if you want help or to talk about how to set this up!
