### ISSUE TITLE
Move to JupyterLab 2.0

### ISSUE THREAD

**Issue by saulshanabrook** [Quansight/ibis-vega-transform#47]
So that we can target https://github.com/jupyterlab/jupyterlab/pull/7381

Mainly just switch phosphor to lumino like https://github.com/jupyterlab/jupyterlab-git/pull/520/files

**Comment by goanpeca** [comment]
@saulshanabrook can we also update jupyter-jaeger ?

At the moment jupyter-jaeger is still pulling phosphor

**Comment by saulshanabrook** [comment]
Yeah it should be as simple as bumping this to the newest beta version and publishing again? https://github.com/Quansight/jupyter-jaeger/blob/67c966c4d1ca42f1a52faf65c729ed5940be93ec/package.json#L33

**Comment by goanpeca** [comment]
Working on this
