### ISSUE TITLE
Fix binder tests

### ISSUE THREAD

**Issue by goanpeca** [Quansight/ibis-vega-transform#58]
```
+ jlpm run build
yarn run v1.21.1
$ tsc
Done in 4.64s.
+ jupyter labextension install jupyterlab-server-proxy-saulshanabrook --no-build
-\|/-\|/-\|/-\|/-\|/-\An error occured.
ValueError: The extension "jupyterlab-server-proxy-saulshanabrook" does not yet support the current version of JupyterLab.
```

**Comment by saulshanabrook** [comment]
Just had to publish it before they published the actual version: https://github.com/jupyterhub/jupyter-server-proxy/issues/139#issuecomment-544763062

Looks like we can just use the real one now: https://github.com/jupyterhub/jupyter-server-proxy/tree/master/jupyterlab-server-proxy

**Comment by goanpeca** [comment]
👍
