### ISSUE TITLE
Ibis-Omnisci import syntax

### ISSUE THREAD

**Issue by kcpevey** [Quansight/ibis-vega-transform#75]
This line https://github.com/Quansight/ibis-vega-transform/blob/5450669937e043a2f0deba2d9139e95c8ecf6876/ibis_vega_transform/query.py#L9 breaks on current master. Ibis is undergoing a refactoring of the backends and it seems that the omnisci backend will (for now) be imported as `from ibis.backends import omniscidb`. 

This will cause a regression with the next release of Ibis. Just thought you should be aware before it happens!

**Comment by saulshanabrook** [comment]
Thank you!
